CREATE DATABASE IF NOT EXISTS bd_clientes;
CREATE DATABASE IF NOT EXISTS bd_cuentas;
CREATE DATABASE IF NOT EXISTS bd_deudores;
CREATE DATABASE IF NOT EXISTS bd_empleados;
CREATE DATABASE IF NOT EXISTS bd_fichas;
CREATE DATABASE IF NOT EXISTS bd_juegos;
CREATE DATABASE IF NOT EXISTS bd_maquinas;
CREATE DATABASE IF NOT EXISTS bd_mesas;
